package com.profiles.app.profile_manager_app.Exceptions;

public class ErrCodes {

    public static String USERNAME_CANNOT_BE_EMPTY_OR_GREATER_THAN_50_CHARACTERS = "USERNAME_CANNOT_BE_EMPTY_OR_GREATER_THAN_50_CHARACTERS";
    public static String USER_ID_CANNOT_BE_EMPTY_OR_GREATER_THAN_50_CHARACTERS = "USER_ID_CANNOT_BE_EMPTY_OR_GREATER_THAN_50_CHARACTERS";
    public static String EMAIL_INVALID_FORMAT_OR_GREATER_THAN_50_CHARACTERS = "EMAIL_INVALID_FORMAT_OR_GREATER_THAN_50_CHARACTERS";
    public static String IMAGE_CANNOT_BE_EMPTY_OR_GREATER_THAN_255_CHARACTERS = "IMAGE_CANNOT_BE_EMPTY_OR_GREATER_THAN_255_CHARACTERS";
    public static String SEX_MUST_BE_MALE_OR_FEMALE = "SEX_MUST_BE_MALE_OR_FEMALE";
    public static String DESCRIPTION_CANNOT_BE_EMPTY_OR_GREATER_THAN_250_CHARACTERS = "DESCRIPTION_CANNOT_BE_EMPTY_OR_GREATER_THAN_250_CHARACTERS";
    public static String BIRTHDATE_CANNOT_BE_EMPTY_OR_INVALID_FORMAT = "BIRTHDATE_CANNOT_BE_EMPTY_OR_INVALID_FORMAT";
    public static String POSITION_CANNOT_BE_EMPTY_OR_INVALID_FORMAT = "POSITION_CANNOT_BE_EMPTY_OR_INVALID_FORMAT";
    public static String USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    public static String USER_NOT_FOUND = "USER_NOT_FOUND";
    public static String COULD_NOT_FIND_USERS_NEAR_YOU= "COULD_NOT_FIND_USERS_NEAR_YOU";
    public static String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
}
